### PR TITLE
fix: update return type of findOneByForeignId to include null

### LINKED ISSUE #614: 🤔 [ISSUE] - findOneByForeignId() can return an empty array
### Description

While there's no bug currently, we need to fix findOneByForeignId() so that it returns `Subscriber | null` just like findOne() :

```
// api/src/chat/repositories/subscriber.repository.ts
/**
   * Finds a single subscriber by his foreign ID (channel's id).
   *
   * @param id - The foreign ID of the subscriber.
   *
   * @returns The found subscriber entity.
   */
  async findOneByForeignId(id: string): Promise<Subscriber> {
    const query = this.findByForeignIdQuery(id);
    const [result] = await this.execute(query, Subscriber);
    return result;
  }
```

### PR DESCRIPTION
**Pull request by TheCoderAdi**
# Motivation

This change ensures that the `findOneByForeignId()` method behaves consistently by returning `Subscriber | null`, just like the `findOne()` method. Adding a `null` check increases reliability and prevents potential errors when the method is called with a foreign ID that doesn't exist. This update improves the code's robustness and aligns with best practices.

Fixes #614 

# Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] I have added unit tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Review by marrouchi — APPROVED** [review]

File: api/src/chat/repositories/subscriber.repository.ts [hunk 1]
```diff
@@ -125,10 +125,10 @@ export class SubscriberRepository extends BaseRepository<
    *
    * @returns The found subscriber entity.
```
Comment (IkbelTalebHssan) [inline api/src/chat/repositories/subscriber.repository.ts:126]:
```suggestion
   * @returns The found subscriber entity, or `null` if no subscriber is found.
```

**Review by IkbelTalebHssan — APPROVED** [review]
Thank you @TheCoderAdi for your contribution LGTM :rocket: :clap: 
Left a minor comment :pray:

File: api/src/chat/repositories/subscriber.repository.ts (hunk 1 above)
Comment (TheCoderAdi) [reply api/src/chat/repositories/subscriber.repository.ts:126]: Thanks for reviewing my contribution. I'll make the suggested change promptly. Appreciate the feedback! 🚀

Comment (IkbelTalebHssan) [reply api/src/chat/repositories/subscriber.repository.ts]: Well done @TheCoderAdi :clap: :clap:
