### PR TITLE
fix: validation bypass when updating block

### LINKED ISSUE #933: 🐛 [BUG] - Validation by pass when updating Block
### Description

When blocks get updated it by passes the front-end validation.

### Reproduction steps

```bash
1. Go to 'visual editor'
2. Drag and drop 'attachment block'
3. Edit the newly created block & upload image
4. Edit the block again and remove the uploaded image
5. Select different tab and Submit
```

### Logs

```bash

```

### Browsers

_No response_

### OS

_No response_

### PR DESCRIPTION
**Pull request by IkbelTalebHssan**
# Motivation

This PR introduces a validation error message when required fields are missing in the block editing form.

Fixes #933

# Type of change:

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added unit tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Summary by CodeRabbit

- **New Features**
  - Added a user-facing error message when required fields are missing in forms, now available in both English and French.
- **Enhancements**
  - Improved tab panel behavior for smoother visibility transitions using CSS, enhancing the user experience.
  - Form error handling now displays a toast notification if required fields are not filled.

### CODE REVIEW

File: frontend/src/app-components/tabs/TabPanel.tsx [hunk 1]
```diff
@@ -24,16 +24,21 @@ export function TabPanel(props: TabPanelProps & GridProps) {
       item
       xs
       role="tabpanel"
-      hidden={value !== index}
       id={`vertical-tabpanel-${index}`}
       aria-labelledby={`vertical-tab-${index}`}
+      sx={{
```
Comment (MohamedAliBouhaouala) [inline frontend/src/app-components/tabs/TabPanel.tsx:29]: This code is causing settings to become cropped in UI rendering.

Comment (IkbelTalebHssan) [reply frontend/src/app-components/tabs/TabPanel.tsx:29]: yes @MohamedAliBouhaouala true I'll fix this :pray:

**Review by MohamedAliBouhaouala — APPROVED** [review]
[Screencast from 2025-04-28 17-45-57.webm](https://github.com/user-attachments/assets/9ef655cc-8616-4270-8859-a690e25dd905)
