### PR TITLE
fix: make SettingType.select inferring options as type

### LINKED ISSUE #752: 🤔 [ISSUE] - make SettingType.select return options type instead returning a string type
### Description

# Description
We can notice that currently the SettingType.select setting is having a string. The idea is to make it returning an inferring type from the options value 

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Logs

```bash

```

### Browsers

_No response_

### OS

_No response_

### PR DESCRIPTION
**Pull request by yassinedorbozgithub**
# Motivation
The main motivation is to make setting with SettingType.select type inferring the options types.

Fixes #752

# Checklist:
- [x] I have performed a self-review of my own code
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by IkbelTalebHssan — APPROVED** [review]

**Comment by abdou6666** [comment]
LGTM :rocket: 

image

**Review by abdou6666 — APPROVED** [review]

File: api/src/setting/index.d.ts [hunk 1]
```diff
@@ -22,10 +24,14 @@ declare global {
             ? { [K in keyof T]: TNativeType<T[K]> }
             : T;
 
+  type SettingValue<K> = K['type'] extends SettingType.select
+    ? K['options'][number]
+    : TNativeType<K['value']>;
+
   type SettingObject<
```
Comment (abdou6666) [inline api/src/setting/index.d.ts:31]: can we export this type, few days ago while writing custom plugins. I wanted to create a private fields containing the args of the plugin and I couldn't type it

Comment (marrouchi) [reply api/src/setting/index.d.ts:31]: @abdou6666 The type is under "global", so it's accessible without the need to export nor import
