### PR TITLE
Fix: update accepted attachments mime types

### LINKED ISSUE #650: Block/Content Attachment Uploader doesn't accept all files.

### PR DESCRIPTION
**Pull request by abdou6666**
# Motivation

This PR:
-  Adds new mimes types
 - Fix issue in the widget where we are not providing which mime types user can send
 - Fix issue in the user avatar where the input doesn't have accept values mime types thus able to pick a PDF as avatar
 
we should check if some of mime types i' have added aren't necessary

Fixes #650

# Type of change:

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] I have performed a self-review of my own code

### CODE REVIEW

**Review by yassinedorbozgithub — CHANGES_REQUESTED** [review]

File: frontend/src/app-components/inputs/FileInput.tsx [hunk 1]
```diff
@@ -71,6 +72,7 @@ const FileUploadButton = forwardRef<HTMLLabelElement, FileUploadButtonProps>(
           value="" // to trigger an automatic reset to allow the same file to be selected multiple times
           sx={{ display: "none" }}
           onChange={handleImportChange}
+          inputProps={{ accept }}
```
Comment (marrouchi) [inline frontend/src/app-components/inputs/FileInput.tsx:75]: There's already a check up in this file, does it become unecessary?

**Review by marrouchi — CHANGES_REQUESTED** [review]

File: frontend/src/app-components/inputs/FileInput.tsx (hunk 1 above)
Comment (abdou6666) [reply frontend/src/app-components/inputs/FileInput.tsx:75]: I think so with that attribute it won't display the options that aren't included in mime types

**Review by marrouchi — APPROVED** [review]

**Review by marrouchi — APPROVED** [review]

**Review by yassinedorbozgithub — APPROVED** [review]
LGTM :+1:
