### PR TITLE
fix: custom plugins displayed unsorted

### LINKED ISSUE #867: 🐛 [BUG] - Random order custom blocks in the sidebar
### Description

The order of custom blocks is inconsistent across sessions. Each time the project is refreshed or restarted, the blocks appear in a different order instead of maintaining their original sequence

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Logs

```bash

```

### Browsers

_No response_

### OS

_No response_

### PR DESCRIPTION
**Pull request by abdou6666**
# Motivation

This PR ensures sorting (based on name) custom plugins before rendering them to ensure display order consistency 

Fixes #867

# Type of change:

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] I have performed a self-review of my own code

### CODE REVIEW

**Comment by MohamedAliBouhaouala** [comment]
Screenshot from 2025-04-02 15-45-50
Screenshot from 2025-04-02 15-47-39


Tested! LGTM !

**Review by MohamedAliBouhaouala — APPROVED** [review]

**Review by yassinedorbozgithub — APPROVED** [review]

**Review by IkbelTalebHssan — APPROVED** [review]

File: frontend/src/components/visual-editor/CustomBlocks.tsx [hunk 1]
```diff
@@ -17,18 +18,22 @@ import { Block, StyledTitle } from "./Aside";
 
 export const CustomBlocks = () => {
   const { t } = useTranslate();
-  const { data: customBlocks } = useFind(
+  const { data: customBlocks = [] } = useFind(
     { entity: EntityType.CUSTOM_BLOCK },
     { hasCount: false },
   );
+  const memoizedCustomBlock = useMemo(
```
Comment (marrouchi) [inline frontend/src/components/visual-editor/CustomBlocks.tsx:25]:
```suggestion
  const memoizedCustomBlocks = useMemo(
```

**Review by marrouchi — CHANGES_REQUESTED** [review]

**Review by IkbelTalebHssan — APPROVED** [review]
