### PR TITLE
fix(api): resolve predefined update hooks bug

### LINKED ISSUE #1134: 🤔 [ISSUE] - API : Make sure "hook:entity:pre/postUpdate" is used across the board
### Description

In certain cases, we are not using hook::pre/postUpdate. This is because, the event wasn't properly implemented.

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Logs

```bash

```

### Browsers

_No response_

### OS

_No response_

### PR DESCRIPTION
**Pull request by yassinedorbozgithub**
# Motivation
The main motivation of this PR is to use base-repository predefined hooks.

Fixes #1134

# Type of change:
- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:
- [x] I have performed a self-review of my own code
- [x] New and existing unit tests pass locally with my changes

## Summary by CodeRabbit

- **Refactor**
	- Improved event handling for NLP entity and value updates to use updated post-update hooks with enhanced parameters and type definitions.
- **Tests**
	- Added new test cases to verify correct triggering and handling of post-update events for NLP entities and values.

### CODE REVIEW

File: api/types/event-emitter.d.ts [hunk 1]
```diff
@@ -189,7 +189,8 @@ declare module '@nestjs/event-emitter' {
 
   type TPostUpdateValidate<T> = FilterQuery<T>;
 
-  type TPostUpdate<T> = THydratedDocument<T>;
+  // TODO this type will be optimized soon in a separated PR
```
Comment (MohamedAliBouhaouala) [inline api/types/event-emitter.d.ts:192]: do we have a corresponding ticket for this?

Comment (yassinedorbozgithub) [reply api/types/event-emitter.d.ts:192]: Yes we have a dedicated issue for that (I have worked on the other issue several times, and if I can estimate the progress, I will say it's ~98% done) 
https://github.com/Hexastack/Hexabot/issues/755

File: api/src/nlp/services/nlp.service.ts [hunk 2]
```diff
@@ -96,15 +97,28 @@ export class NlpService {
...
-      this.logger.debug('Updated entity successfully synced!', entity);
-    } catch (err) {
-      this.logger.error('Unable to sync updated entity', err);
+  @OnEvent('hook:nlpEntity:postUpdate')
+  async handleEntityPostUpdate(
+    _query: Query<
+      Document<NlpEntity>,
+      Document<NlpEntity>,
+      unknown,
+      NlpEntity,
```
Comment (MohamedAliBouhaouala) [inline api/src/nlp/services/nlp.service.ts:106]: Can we update ``JS docs`` to account for newly added method arguments?

File: api/src/nlp/services/nlp.service.ts [hunk 3]
```diff
@@ -174,15 +188,28 @@ export class NlpService {
...
-      this.logger.debug('Updated value successfully synced!', value);
-    } catch (err) {
-      this.logger.error('Unable to sync updated value', err);
+  @OnEvent('hook:nlpValue:postUpdate')
+  async handleValuePostUpdate(
+    _query: Query<
+      Document<NlpValue, any, any>,
+      Document<NlpValue, any, any>,
+      unknown,
+      NlpValue,
```
Comment (MohamedAliBouhaouala) [inline api/src/nlp/services/nlp.service.ts:203]: same here

File: api/src/nlp/services/nlp.service.ts (hunk 2 above)
Comment (yassinedorbozgithub) [reply api/src/nlp/services/nlp.service.ts:106]: Yes for sure, happy to do this :technologist:

File: api/src/nlp/services/nlp.service.ts (hunk 3 above)
Comment (yassinedorbozgithub) [reply api/src/nlp/services/nlp.service.ts:203]: If i'm not mistaken you mean updating the JSDoc.
Happy to apply the changes :magic_wand:

File: api/src/nlp/repositories/nlp-entity.repository.spec.ts [hunk 4]
```diff
@@ -228,4 +228,28 @@ describe('NlpEntityRepository', () => {
       expect(nlpEntity).toEqualPayload(result);
     });
   });
+
+  describe('postUpdate', () => {
+    it('should update an NlpEntity and trigger a postUpdate event', async () => {
+      nlpEntityRepository.eventEmitter.once(
+        'hook:nlpEntity:postUpdate',
+        async (...[query, updated]) => {
+          const spy1 = jest.spyOn(llmNluHelper, 'updateEntity');
```
Comment (MohamedAliBouhaouala) [inline api/src/nlp/repositories/nlp-entity.repository.spec.ts]:
```ts
const helperSpy
```

File: api/src/nlp/repositories/nlp-value.repository.spec.ts [hunk 5]
```diff
@@ -250,4 +250,28 @@ describe('NlpValueRepository', () => {
       expect(nlpValue).toEqualPayload(result);
     });
   });
+
+  describe('postUpdate', () => {
+    it('should update an NlpValue and trigger a postUpdate event', async () => {
+      nlpValueRepository.eventEmitter.once(
+        'hook:nlpValue:postUpdate',
+        async (...[query, updated]) => {
+          const spy1 = jest.spyOn(llmNluHelper, 'updateValue');
```
Comment (MohamedAliBouhaouala) [inline api/src/nlp/repositories/nlp-value.repository.spec.ts]:
```ts
const helperSpy
```

**Comment by marrouchi** [comment]
@coderabbitai review

File: api/types/event-emitter.d.ts [hunk 6]
```diff
@@ -132,10 +132,10 @@ declare module '@nestjs/event-emitter' {
     menu: TDefinition<Menu>;
     language: TDefinition<Language>;
     translation: TDefinition<Translation>;
-    nlpEntity: TDefinition<NlpEntity, { update: NlpEntity }>;
+    nlpEntity: TDefinition<NlpEntity>;
     nlpSampleEntity: TDefinition<NlpSampleEntity>;
     nlpSample: TDefinition<NlpSample>;
-    nlpValue: TDefinition<NlpValue, { update: NlpValue }>;
+    nlpValue: TDefinition<NlpValue>;
     setting: TDefinition<Setting>;
```
[the remark this answers is not in the document]
Comment (yassinedorbozgithub) [reply api/types/event-emitter.d.ts:139]: Please note that the second generic of TDefinition have a default type value
