### PR TITLE
fix: User module issues

### LINKED ISSUE #538: 🤔 [ISSUE] - User Module strictNullChecks issues
### Description

User Module includes types errors

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Logs

_No response_

### Browsers

_No response_

### OS

_No response_

### PR DESCRIPTION
**Pull request by yassinedorbozgithub**
# Motivation
The motivation of this PR is to resolve User Module null checks issues

Fixes #538 

# Type of change:

# Checklist:
- [x] I have performed a self-review of my own code
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: api/src/user/controllers/user.controller.ts [hunk 1]
```diff
@@ -248,7 +248,9 @@ export class ReadWriteUserController extends ReadOnlyUserController {
         roles: (await this.roleService.findAll())
           .filter((role) => user.roles.includes(role.id))
           .map((role) => role.id),
-        avatar: (await this.attachmentService.findOne(user.avatar))?.id,
+        avatar: user.avatar
+          ? (await this.attachmentService.findOne(user.avatar))?.id
+          : undefined,
```
Comment (marrouchi) [inline api/src/user/controllers/user.controller.ts:253]: avatar should be either ObjectId or null

File: api/src/user/passport/session.serializer.ts [hunk 2]
```diff
@@ -29,9 +32,9 @@ export class AuthSerializer extends PassportSerializer {
 
   async deserializeUser(
     payload: SessionUser,
-    done: (err: Error, user: SessionUser) => void,
+    done: (err: Error | null, user: SessionUser | null) => void,
   ) {
-    const user = await this.userService.findOne(payload.id);
+    const user = payload.id ? await this.userService.findOne(payload.id) : null;
     user ? done(null, user) : done(null, null);
```
Comment (marrouchi) [inline api/src/user/passport/session.serializer.ts:38]:
```suggestion
    done(null, user);
```

File: api/src/user/schemas/user.schema.ts [hunk 3]
```diff
@@ -112,7 +112,7 @@ export class User extends UserStub {
   roles: string[];
 
   @Transform(({ obj }) => obj.avatar?.toString() || null)
-  avatar?: string;
+  avatar?: string | null;
```
Comment (marrouchi) [inline api/src/user/schemas/user.schema.ts:115]:
```suggestion
  avatar: string | null;
```

**Review by marrouchi — CHANGES_REQUESTED** [review]

File: api/src/user/controllers/user.controller.ts (hunk 1 above)
Comment (yassinedorbozgithub) [reply api/src/user/controllers/user.controller.ts]: I have update the logic to support null value

**Review by marrouchi — APPROVED** [review]
