### PR TITLE
fix: Show quick replies in Console Chat Widget

### LINKED ISSUE #993: [Bug] Console Chat Widget doesn't show quick replies
Console Chat Widget doesn't show quick replies because it's receiving messages from the global websocket connection. If the last message received is not a quick replies message, the suggestions disappear.

## How to reproduce

1- Open Visual Editor chat widget and trigger a quick replies block
2- Open the Inbox in another tab

### PR DESCRIPTION
**Pull request by yassinedorbozgithub**
# Motivation
The updates introduced by this PR are : 
- (API) Enhancing subscribe method returning type for web-socket notification room.
- (API) Adding new joinNotificationSockets method enabling to join sockets without channel from the current session.
- (API) Add jest env compatibility to websocket cors.
- (API) Add jest env compatibility to createAndStoreSession.
- (Frontend) Adding missing subscribe logic for the pages other then inbox page.
- (Frontend) Updating HeaderProps props to be optional (needed for AnonymousLayout).
- (Frontend) Splitting layout to two layouts  (AuthenticatedLayout, AnonymousLayout).
- (Widget) Adding support to showing quick replies after refreshing the page. (ChatProvider, UserSubscription)

Fixes #993

# Checklist:
- [x] I have performed a self-review of my own code
- [x] New and existing unit tests pass locally with my changes

## Summary by CodeRabbit

- **New Features**
  - Introduced separate layouts for authenticated and anonymous users, each with tailored structure and components.
  - Added real-time message and subscriber updates in the authenticated layout for enhanced interactivity.

- **Refactor**
  - Simplified layout management by delegating to dedicated layout components based on user authentication status.
  - Improved typing for header component props to allow for greater flexibility.
  - Converted WebSocket session handling and subscription methods to asynchronous operations for improved reliability.

- **Style**
  - Updated copyright years to 2025.

- **Chores**
  - Improved internal type definitions and response structures for WebSocket communication.
  - Enhanced chat suggestion handling by initializing and formatting quick replies for better user experience.
  - Refined WebSocket gateway CORS configuration to allow all origins in test environments.
  - Added comprehensive tests for WebSocket subscription and notification socket management methods.

### CODE REVIEW

File: widget/src/providers/ChatProvider.tsx [hunk 1]
```diff
@@ -327,6 +325,11 @@ const ChatProvider: React.FC<{
             queryParams,
           ).toString()}`,
         );
+        const quickReplies = getQuickReplies(body.messages.at(-1));
+
+        if (quickReplies.length) {
+          setSuggestions(quickReplies);
+        }
```
Comment (marrouchi) [inline widget/src/providers/ChatProvider.tsx:332]:
```suggestion
          setSuggestions(quickReplies);
```

File: api/src/websocket/websocket.gateway.ts [hunk 2]
```diff
@@ -405,4 +422,45 @@ export class WebsocketGateway
...
+    sessionId: string,
+  ): Promise<RemoteSocket<DefaultEventsMap, any>[]> {
+    if (!sessionId) {
+      throw new Error('SessionId is required!');
+    }
+
+    return (await this.io.fetchSockets()).filter(
+      ({ handshake, data }) =>
+        !handshake.query.channel && data.sessionID === sessionId,
+    );
```
Comment (marrouchi) [inline api/src/websocket/websocket.gateway.ts:442]:
```suggestion
    const allSockets = await this.io.fetchSockets();
    return allSockets.filter(
      ({ handshake, data }) =>
        !handshake.query.channel && data.sessionID === sessionId,
    );
```

File: api/src/websocket/websocket.gateway.ts [hunk 3]
```diff
@@ -405,4 +422,45 @@ export class WebsocketGateway
...
+  async getNotificationSockets(
+    sessionId: string,
+  ): Promise<RemoteSocket<DefaultEventsMap, any>[]> {
+    if (!sessionId) {
+      throw new Error('SessionId is required!');
+    }
+
+    return (await this.io.fetchSockets()).filter(
+      ({ handshake, data }) =>
+        !handshake.query.channel && data.sessionID === sessionId,
```
Comment (marrouchi) [inline api/src/websocket/websocket.gateway.ts:441]: The channel needs to be "console", right ?

**Review by marrouchi — CHANGES_REQUESTED** [review]

File: api/src/websocket/websocket.gateway.ts (hunk 3 above)
Comment (yassinedorbozgithub) [reply api/src/websocket/websocket.gateway.ts:441]: From my understanding this code will make sockets without channel query param (global) joining message and subscriber rooms to be able to see global events (updateSubscriber, messageReceived, messageSent) it can be helpful to show UI notifications

Comment (marrouchi) [reply api/src/websocket/websocket.gateway.ts:442]: Ah yes you are right 🙏

**Review by marrouchi — APPROVED** [review]
