### PR TITLE
fix: trigger patterns management

### LINKED ISSUE #1094: 🤔 [ISSUE] - Error when attempting to remove a non-existent trigger in previous blocks
When attempting to remove a trigger using a command or UI action, the system throws an error if the specified trigger does not exist within the "previous blocks" (e.g., in a workflow, automation, or similar sequential configuration). This issue prevents clean removal operations and can lead to confusion when managing triggers.

### PR DESCRIPTION
**Pull request by marrouchi**
# Motivation

Implement useSimpleFieldArray for managing dynamic patterns in the TriggersForm.

Fixes #1094

# Type of change:

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added unit tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Summary by CodeRabbit

* **New Features**
  * Improved pattern input management with dynamic addition, removal, and editing of patterns directly integrated into forms.
  * Added support for multiple pattern types including text, regex, NLP, payloads, menus, content, and outcomes with specialized input controls.
  * Introduced stable handling of pattern arrays with enhanced form state synchronization.

* **Refactor**
  * Centralized pattern state management within the form context for streamlined interaction.
  * Removed redundant wrappers around pattern inputs for cleaner and more direct form integration.
  * Replaced pattern type definitions with a strongly typed enum for improved consistency.
  * Simplified component structures and updated input components to use direct props and callbacks.

* **Bug Fixes**
  * Enhanced validation and immediate error feedback for regex and text pattern inputs.

* **Chores**
  * Updated utility functions for string formatting to improve consistency in path formatting.

### CODE REVIEW

File: frontend/src/components/visual-editor/form/inputs/triggers/PatternsInput.tsx [hunk 1]
```diff
@@ -117,46 +127,114 @@ const PatternsInput: FC<PatternsInputProps> = ({ value, onChange }) => {
...
+                        if (!isRegex(extractRegexBody(pattern as string))) {
+                          setError(`patterns.${idx}`, {
+                            type: "manual",
+                            message: t("message.regex_is_invalid"),
+                          });
+                        } else {
+                          clearErrors(`patterns.${idx}`);
+                        }
+
+                        update(idx, formatWithSlashes(pattern));
```
Comment (medchedli) [inline frontend/src/components/visual-editor/form/inputs/triggers/PatternsInput.tsx]:
```suggestion
                        const patternBody = e.target.value;

                        if (!isRegex(patternBody)) {
                          setError(`patterns.${idx}`, {
                            type: "manual",
                            message: t("message.regex_is_invalid"),
                          });
                        } else {
                          clearErrors(`patterns.${idx}`);
                        }

                        update(idx, formatWithSlashes(patternBody));
```

**Review by medchedli — CHANGES_REQUESTED** [review]
`e.target.value` from the input is just the regex body (without slashes). This causes the validation to always run on an empty string

File: frontend/src/hooks/useSimpleFieldArray.ts [hunk 2]
```diff
@@ -0,0 +1,65 @@
...
+  const update = (index: number, updated: T) => {
+    setValue(`${name}.${index}` as const, updated, {
+      shouldValidate: true,
+      shouldDirty: true,
+    });
+  };
+  const fields = values.map((v, i) => ({ value: v, id: ids.current[i] })) as FieldWithId<T>[];
+
+  return { fields, append, remove, update };
+}
```
Comment (medchedli) [inline frontend/src/hooks/useSimpleFieldArray.ts]: This file requires linting : The file is missing a newline at the end

File: frontend/src/components/visual-editor/form/inputs/triggers/PatternsInput.tsx [hunk 3]
```diff
@@ -14,22 +14,55 @@ import PsychologyAltIcon from "@mui/icons-material/PsychologyAlt";
...
 import { SXStyleOptions } from "@/utils/SXStyleOptions";
-import { createValueWithId, ValueWithId } from "@/utils/valueWithId";
 
-import { getInputControls } from "../../utils/inputControls";
-
-import PatternInput from "./PatternInput";
+import { OutcomeInput } from "./OutcomeInput";
+import { PostbackInput } from "./PostbackInput";
 
+const getPatternType = (pattern: Pattern): PatternType => {
```
Comment (medchedli) [inline frontend/src/components/visual-editor/form/inputs/triggers/PatternsInput.tsx:31]: I sugget we add null check for pattern in `getPatternType`

File: frontend/src/components/visual-editor/form/inputs/triggers/PatternsInput.tsx [hunk 4]
```diff
@@ -117,46 +127,114 @@ const PatternsInput: FC<PatternsInputProps> = ({ value, onChange }) => {
...
+                )}
+                <Box display="flex" flexGrow={1}>
+                  {patternType === "nlp" && (
+                    <NlpPatternSelect
+                      patterns={value as NlpPattern[]}
+                      onChange={(patterns) => update(idx, patterns)}
+                      fullWidth={true}
+                    />
+                  )}
+                  {["payload", "content", "menu"].includes(patternType) ? (
```
Comment (MohamedAliBouhaouala) [inline frontend/src/components/visual-editor/form/inputs/triggers/PatternsInput.tsx]: Let's use `PatternTypeEnum` instead of hardcoded string values

File: frontend/src/components/visual-editor/form/inputs/triggers/PatternsInput.tsx (hunk 3 above)
Comment (marrouchi) [reply frontend/src/components/visual-editor/form/inputs/triggers/PatternsInput.tsx:31]: I think there's already a check.

File: frontend/src/hooks/useSimpleFieldArray.ts (hunk 2 above)
Comment (MohamedAliBouhaouala) [inline frontend/src/hooks/useSimpleFieldArray.ts]: Will we need other operations in the future ? other than `remove`, `update` & `append`

Comment (marrouchi) [reply frontend/src/hooks/useSimpleFieldArray.ts]: Maybe, we will be using useFieldArray() from 'react-hook-form' in other case. Specifically for patterns we won't need any additional ones.

File: frontend/src/components/visual-editor/form/inputs/triggers/PatternsInput.tsx (hunk 4 above)
Comment (marrouchi) [reply frontend/src/components/visual-editor/form/inputs/triggers/PatternsInput.tsx]: Done

File: frontend/src/hooks/useSimpleFieldArray.ts (hunk 2 above)
Comment (MohamedAliBouhaouala) [reply frontend/src/hooks/useSimpleFieldArray.ts]: Perhaps, a TODO comment or something similar would be good to keep track of it. Just a small suggestion, nothing critical

File: frontend/src/components/visual-editor/form/inputs/triggers/PatternsInput.tsx (hunk 3 above)
Comment (medchedli) [reply frontend/src/components/visual-editor/form/inputs/triggers/PatternsInput.tsx:31]: By type definition, pattern can take the value null if the data or form state includes it. I couldn't find where we are preventing null values in the current implementation.

File: frontend/src/components/visual-editor/form/inputs/triggers/PatternsInput.tsx [hunk 5]
```diff
@@ -117,46 +129,114 @@ const PatternsInput: FC<PatternsInputProps> = ({ value, onChange }) => {
...
+                      label={t("label.text")}
+                      error={!!errors?.patterns?.[idx]}
+                      helperText={errors?.patterns?.[idx]?.message}
+                      onChange={(e) => {
+                        const pattern = e.target.value;
+
+                        if (!pattern) {
+                          setError(`patterns.${idx}`, {
+                            type: "manual",
+                            message: t("message.required"),
```
Comment (medchedli) [inline frontend/src/components/visual-editor/form/inputs/triggers/PatternsInput.tsx]:
```suggestion
                            message: t("message.text_is_required"),
```

**Review by medchedli — CHANGES_REQUESTED** [review]

**Review by yassinedorbozgithub — CHANGES_REQUESTED** [review]
Facing this issue when adding a new pattern
<video src="https://github.com/user-attachments/assets/4450a3fd-5c21-4414-b7e0-b5006d727217"></video>

**Review by MohamedAliBouhaouala — APPROVED** [review]

**Review by yassinedorbozgithub — APPROVED** [review]

File: frontend/src/components/visual-editor/form/inputs/triggers/PatternsInput.tsx [hunk 6]
```diff
@@ -113,50 +104,63 @@ const PatternsInput: FC<PatternsInputProps> = ({ value, onChange }) => {
...
+                      patternType === PatternType.regex &&
+                      (value === "//" || !isRegex(value as string))
+                    ) {
+                      return t("message.regex_is_invalid");
+                    } else if (patternType === PatternType.text && !value) {
+                      return t("message.text_is_required");
+                    } else if (!value) {
+                      return t("message.required");
+                    }
+
```
Comment (medchedli) [inline frontend/src/components/visual-editor/form/inputs/triggers/PatternsInput.tsx]:
```suggestion
                    if (patternType === PatternType.regex) {
                      if (value === "//") {
                        return t("message.regex_is_empty");
                      } else if (!isRegex(extractRegexBody(value as string)))
                        return t("message.regex_is_invalid");
                    } else if (patternType === PatternType.text && !value) {
                      return t("message.text_is_required");
                    } else if (!value) {
                      return t("message.required");
                    }

```

**Review by yassinedorbozgithub — CHANGES_REQUESTED** [review]
Doing a new iteration of review i notice this bug happening with regex validation 
<video src="https://github.com/user-attachments/assets/2151fa2a-b2ad-49c6-b124-ba19478d3a00"> </video>

**Review by yassinedorbozgithub — APPROVED** [review]
