### PR TITLE
fix: persist subscriber avatars

### LINKED ISSUE #474: 🐛 [BUG] - avatars are not persistent after restarting the API
### Description

# Description
We can notice that avatars are not persistent after restarting the API.

### Reproduction steps

```bash
1. Go to inbox
2. Subscriber avatar are empty
```

### Logs

_No response_

### Browsers

_No response_

### OS

_No response_

### PR DESCRIPTION
**Pull request by yassinedorbozgithub**
# Motivation
The main motivation of this PR is to fix the subscriber avatars mounting issues

Fixes #474

# Type of change:
- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:
- [x] I have performed a self-review of my own code
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by marrouchi — APPROVED** [review]

File: api/src/config/index.ts [hunk 1]
```diff
@@ -106,7 +106,9 @@ export const config: Config = {
     uploadDir:
       (process.env.UPLOAD_DIR && join(process.cwd(), process.env.UPLOAD_DIR)) ??
       join(process.cwd(), 'uploads'),
-    avatarDir: process.env.AVATAR_DIR ?? join(process.cwd(), 'avatars'),
+    avatarDir:
+      (process.env.AVATAR_DIR && join(process.cwd(), process.env.AVATAR_DIR)) ??
+      join(process.cwd(), 'avatars'),
```
Comment (marrouchi) [inline api/src/config/index.ts:111]:
```suggestion
      (process.env.AVATAR_DIR ? join(process.cwd(), process.env.AVATAR_DIR)) :
      join(process.cwd(), 'avatars'),
```

File: api/src/config/index.ts [hunk 2]
```diff
@@ -106,7 +106,9 @@ export const config: Config = {
     uploadDir:
       (process.env.UPLOAD_DIR && join(process.cwd(), process.env.UPLOAD_DIR)) ??
       join(process.cwd(), 'uploads'),
```
Comment (marrouchi) [inline api/src/config/index.ts:108]:
```suggestion
    uploadDir:
      (process.env.UPLOAD_DIR ? join(process.cwd(), process.env.UPLOAD_DIR)) :
      join(process.cwd(), 'uploads'),
```

**Review by marrouchi — CHANGES_REQUESTED** [review]
