### PR TITLE
fix(frontend): enhance SearchPayload typing [main<-1247]

### LINKED ISSUE #1247: 🤔 [ISSUE] - useSearch returned searchPayload partial typing
### Description
The **searchPayload** from **useSearch** hook has wrong types. It causes errors when using the data.

### Expected
searchPayload should have the correct type so we can use it safely.

### Steps to Reproduce
1. Use the useSearch hook.
2. Check the type of searchPayload.

### Fix Needed
Update the type of searchPayload to match the expected data.

### PR DESCRIPTION
**Pull request by yassinedorbozgithub**
# Motivation
The main motivations of this PR are : 
- To enhance **useSearch** hook returned **searchPayload** typing
- To enhance **useInfiniteLiveSubscribers**, **useInfiniteLiveMessages** hooks **searchPayload** prop typing
- To fix media-library where.or from object to array of object

Fixes #1247

# Checklist:
- [x] I have performed a self-review of my own code
- [x] New and existing unit tests pass locally with my changes

## Summary by CodeRabbit

* **Refactor**
  * Improved type safety and parameter handling in search-related features for more robust filtering and searching.
  * Enhanced type definitions across components and hooks for better consistency and maintainability.
  * Updated attachment handling to support multiple resource references per item.
  * Refined language and NLP sample data structures to support additional pattern information.
  * Standardized entity type usage in search hooks across multiple components for consistency.
  * Strengthened filtering capabilities with new interfaces and generics for various entities.

* **Chores**
  * Updated copyright year.
  * Enhanced internal type definitions to support more flexible and precise search options.

### CODE REVIEW

File: frontend/src/hooks/useSearch.tsx [hunk 1]
```diff
@@ -19,15 +24,15 @@ import { useUrlQueryParam } from "./useUrlQueryParam";
 const buildOrParams = <T,>({ params, searchText }: TBuildParamProps<T>) => ({
   or: params?.map((field) => ({
     [field]: { contains: searchText },
-  })),
+  })) as IlikeParam<T>[],
```
Comment (MohamedAliBouhaouala) [inline frontend/src/hooks/useSearch.tsx:28]: You mean `as OrParam` ?

File: frontend/src/hooks/useSearch.tsx [hunk 2]
```diff
@@ -19,15 +24,15 @@ import { useUrlQueryParam } from "./useUrlQueryParam";
...
 });
 const buildILikeParams = <T,>({ params, searchText }: TBuildParamProps<T>) =>
   params?.reduce(
     (acc, field) => ({
       ...acc,
       [field]: { contains: searchText },
     }),
-    {},
+    {} as IlikeParam<T>,
```
Comment (MohamedAliBouhaouala) [inline frontend/src/hooks/useSearch.tsx:36]: Why type casting here despite not violating any typing rules?

File: frontend/src/hooks/useSearch.tsx [hunk 3]
```diff
@@ -49,26 +54,15 @@ const buildNeqInitialParams = <T,>({
         "!=": Object.entries(obj)[0][1],
       },
     }),
-    {},
+    {} as NeqParam<T>,
```
Comment (MohamedAliBouhaouala) [inline frontend/src/hooks/useSearch.tsx:58]: same question here

File: frontend/src/hooks/useSearch.tsx (hunk 1 above)
Comment (yassinedorbozgithub) [reply frontend/src/hooks/useSearch.tsx:28]: No, when we found **{contains:  'anyText''}** this means that the item is **IlikeParam**

File: frontend/src/hooks/useSearch.tsx (hunk 2 above)
Comment (yassinedorbozgithub) [reply frontend/src/hooks/useSearch.tsx:36]: I'm not sure, happy if you have suggestions

File: frontend/src/hooks/useSearch.tsx (hunk 3 above)
Comment (yassinedorbozgithub) [reply frontend/src/hooks/useSearch.tsx:58]: https://github.com/Hexastack/Hexabot/pull/1250#discussion_r2219674092

File: frontend/src/types/attachment.types.ts [hunk 4]
```diff
@@ -46,7 +46,7 @@ export interface IAttachmentAttributes {
   location: string;
   url: string;
   channel?: Record<string, any>;
-  resourceRef: AttachmentResourceRef;
+  resourceRef: AttachmentResourceRef[];
```
[the remark this answers is not in the document]
Comment (medchedli) [reply frontend/src/types/attachment.types.ts]: The change to `resourceRef: AttachmentResourceRef[]` is a non-breaking refactoring. It corrects a type mismatch between the frontend and backend.

File: frontend/src/types/language.types.ts [hunk 5]
```diff
@@ -9,14 +9,21 @@
...
+  isDefault: boolean;
+  isRTL: boolean;
+};
 
 export interface ILanguageAttributes {
   title: string;
   code: string;
   isDefault: boolean;
   isRTL: boolean;
+  patterns: NlpPattern[];
```
Comment (medchedli) [inline frontend/src/types/language.types.ts]: I don't think that this addition is needed in `ILanguageAttributes` interface
```suggestion
```

Comment (yassinedorbozgithub) [reply frontend/src/types/language.types.ts]: > I don't think that this addition is needed

You are right, nice catch :rocket:

File: frontend/src/types/attachment.types.ts (hunk 4 above)
[the remark this answers is not in the document]
Comment (marrouchi) [reply frontend/src/types/attachment.types.ts]: @yassinedorbozgithub Are you sure this is an array?

File: frontend/src/types/language.types.ts [hunk 6]
```diff
@@ -10,7 +10,12 @@ import { EntityType, Format } from "@/services/types";
 
 import { IBaseSchema, IFormat, OmitPopulate } from "./base.types";
 
-export type ILanguages = Record<string, string>;
+export type ILanguages = {
```
Comment (marrouchi) [inline frontend/src/types/language.types.ts]: Since it's same as ILanguageAttributes, why don't we re-use ILanguageAttributes ?

File: frontend/src/types/nlp-sample.types.ts [hunk 7]
```diff
@@ -24,6 +25,7 @@ export interface INlpSampleAttributes {
   type?: NlpSampleType;
   entities: string[];
   language: string | null;
+  patterns?: NlpPattern[];
```
Comment (marrouchi) [inline frontend/src/types/nlp-sample.types.ts]: Do we have patterns here ?

File: frontend/src/components/inbox/hooks/useInfiniteLiveSubscribers.ts [hunk 8]
```diff
@@ -32,7 +34,7 @@ export const useInfiniteLiveSubscribers = (props: {
       ...props.searchPayload.where,
       ...(props.channels.length > 0 && {
         or: [
-          ...(props.searchPayload.where.or || []),
+          ...(props.searchPayload.where?.or || []),
           ...props.channels.map((channel) => ({
```
Comment (MohamedAliBouhaouala) [inline frontend/src/components/inbox/hooks/useInfiniteLiveSubscribers.ts]: Line 46 to 50 
```ts
{
            assignedTo: {
              "!=": user?.id,
            },
          }
```
Is it "!=" or "=!"

File: frontend/src/types/attachment.types.ts (hunk 4 above)
[the remark this answers is not in the document]
Comment (yassinedorbozgithub) [reply frontend/src/types/attachment.types.ts]: @marrouchi yes, i'm sure

File: frontend/src/components/inbox/hooks/useInfiniteLiveSubscribers.ts (hunk 8 above)
Comment (yassinedorbozgithub) [reply frontend/src/components/inbox/hooks/useInfiniteLiveSubscribers.ts]: Nice catch :rocket:

File: frontend/src/types/language.types.ts (hunk 6 above)
Comment (yassinedorbozgithub) [reply frontend/src/types/language.types.ts]: No, because ILanguageAttributes will be used for payloads.
This impact that useFind(frontend/src/components/translations/TranslationForm.tsx) will accept any params

File: frontend/src/types/nlp-sample.types.ts (hunk 7 above)
Comment (yassinedorbozgithub) [reply frontend/src/types/nlp-sample.types.ts]: No, a filters type logic is pushed to differentiate between payloads and filters typing

File: frontend/src/types/attachment.types.ts (hunk 4 above)
[the remark this answers is not in the document]
Comment (yassinedorbozgithub) [reply frontend/src/types/attachment.types.ts]: A filters type logic is pushed to differentiate between payloads and filters typing

File: frontend/src/components/inbox/hooks/useInfiniteLiveSubscribers.ts (hunk 8 above)
Comment (MohamedAliBouhaouala) [inline frontend/src/components/inbox/hooks/useInfiniteLiveSubscribers.ts]: I don't think we'd need the type casting at the end. We just have to type it at the start and type cast this one. This code block is causing typing ambiguities 
```ts
...props.channels.map((channel) => ({
    "channel.name": channel,
  })
),
```

Comment (yassinedorbozgithub) [reply frontend/src/components/inbox/hooks/useInfiniteLiveSubscribers.ts]: It's a good i will try to find how i can implemented :mage:

**Review by MohamedAliBouhaouala — APPROVED** [review]
