### PR TITLE
fix: location does not display in inbox conversation

### LINKED ISSUE #352: 🐛 [BUG] - Received Location Fails to Display in Inbox Conversation
### Description

When receiving a location, the location isn't displayed in the inbox conversation.

**Expected Behavior:**

  The received location should be displayed clearly within the inbox conversation.

image
image

### Reproduction steps

```bash
1. Send your location in the widget on visual editor
2. Go to 'inbox' and open the converstaion
3. See error
```

### Logs

_No response_

### Browsers

_No response_

### OS

_No response_

### PR DESCRIPTION
**Pull request by abdou6666**
# Motivation

This PR fixes a bug where when user sends their `location` it displays empty message in the `inbox`

Fixes #352 

# Type of change:

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added unit tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: frontend/src/components/inbox/components/Chat.tsx [hunk 1]
```diff
@@ -92,13 +94,33 @@ export function Chat() {
...
         >
-          {messages.map((message, i) => {
+          {messages.map((message: any, i) => {
             const position = getMessagePosition(
               message,
               messages[i - 1],
               messages[i + 1],
             );
 
+            if (message?.message?.type === "location") {
```
Comment (marrouchi) [inline frontend/src/components/inbox/components/Chat.tsx:104]: I would suggest to move this to the getMessageContent().

**Review by marrouchi — CHANGES_REQUESTED** [review]

**Comment by abdou6666** [comment]
image

File: frontend/src/components/inbox/components/GeolocationMessage.tsx [hunk 2]
```diff
@@ -0,0 +1,63 @@
...
+import { useRef } from "react";
+
+export interface GeolocationMessageProps {
+  message: {
+    type: "location";
+    coordinates: {
+      lat: number;
+      lon: number;
+    };
+  };
```
Comment (marrouchi) [inline frontend/src/components/inbox/components/GeolocationMessage.tsx:18]: You can re-use the type StdIncomingLocationMessage

File: frontend/src/components/inbox/components/GeolocationMessage.tsx [hunk 3]
```diff
@@ -0,0 +1,63 @@
...
+  const iframeRef = useRef<HTMLDivElement>(null);
+
+  if (!("coordinates" in message)) {
+    throw new Error("Unable to find coordinates");
+  }
+
+  const coordinates = {
+    lat: message?.coordinates?.lat || 0.0,
+    lng: message?.coordinates?.lon || 0.0,
+  };
```
Comment (marrouchi) [inline frontend/src/components/inbox/components/GeolocationMessage.tsx:31]: How about we deconstruct ?
```suggestion
  const {lat, lon} = message?.coordinates || {lat: 0.0, lng: 0.0};
```

**Review by marrouchi — CHANGES_REQUESTED** [review]
Looks good, left a few comments.

File: frontend/src/components/inbox/components/GeolocationMessage.tsx [hunk 4]
```diff
@@ -0,0 +1,63 @@
...
+      lat: number;
+      lon: number;
+    };
+  };
+}
+
+const GeolocationMessage: React.FC<GeolocationMessageProps> = ({ message }) => {
+  const iframeRef = useRef<HTMLDivElement>(null);
+
+  if (!("coordinates" in message)) {
```
Comment (yassinedorbozgithub) [inline frontend/src/components/inbox/components/GeolocationMessage.tsx:24]: From my understanding any code after this check will have an existing **message.coordinates** and based on the **StdIncomingLocationMessage** type the **lat** and the **lon** are required fields.

I'm thinking, it is maybe required to test the existing of required fields and give them default values
or/and it's a adaption step to transform the response to a standard format 0 => 0.0 
or/and it's better to a have a type adapted to the location response with optional props **lat**, **lon**

**Review by marrouchi — APPROVED** [review]

**Review by yassinedorbozgithub — CHANGES_REQUESTED** [review]

**Review by IkbelTalebHssan — APPROVED** [review]
LGTM :rocket: 
image
