### PR TITLE
fix: add no result found message

### LINKED ISSUE #885: 💡 [REQUEST] - Add “No result found” Message in Inbox Page When Searching for Subscribers
### Start Date

_No response_

### Implementation PR

_No response_

### Reference Issues

_No response_

### Summary

When searching for subscribers on the Inbox page, if no subscribers match the search criteria, the interface currently displays a blank or empty state. To enhance user experience and provide better feedback, a message stating “No result found” should be displayed when no matching results are found.

### Basic Example

- Display the message “No result found” centered within the subscriber list area when the search returns no results.
- Ensure the message is styled to be visually consistent with the rest of the UI (e.g., font, size, color, etc.).
- Maintain responsiveness and compatibility with different screen sizes.
- Ensure accessibility by providing appropriate aria-label or similar attributes if necessary.

### Drawbacks

None

### Unresolved questions

_No response_

### PR DESCRIPTION
**Pull request by IkbelTalebHssan**
# Motivation

This PR improves the user experience in the Inbox module by adding a fallback message when no subscribers match the current search/filter criteria. Previously, the UI remained empty without feedback, which could be confusing to users.

Fixes #885 

# Type of change:

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added unit tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Summary by CodeRabbit

- **New Features**
  - Enhanced the subscribers view: if no subscribers are available, users now see a clear message instead of an empty list.

### CODE REVIEW

**Review by abdou6666 — APPROVED** [review]

File: frontend/src/components/inbox/components/ConversationsList.tsx [hunk 1]
```diff
@@ -87,6 +87,12 @@ export const SubscribersList = (props: {
             </Conversation>
           ))}
         </ConversationList>
+      ) : (
+        <Grid paddingX={2}>
+          <p style={{ textAlign: "center", color: "#999", marginTop: "1rem" }}>
+            {t("message.no_result_found")}
+          </p>
+        </Grid>
```
Comment (yassinedorbozgithub) [inline frontend/src/components/inbox/components/ConversationsList.tsx:95]:
```suggestion
        <Grid p={1} color="gray" textAlign="center">
          {t("message.no_result_found")}
        </Grid>
```

**Review by medchedli — APPROVED** [review]
