### PR TITLE
fix(frontend): allow fallback block to be empty

### LINKED ISSUE #553: 🐛 [BUG] - Internal server error when setting the fallback block to empty
### Description

Internal server error when setting the fallback block to empty.

### Reproduction steps

```bash
Go to Settings > Chatbot.
If the fallback block is empty, try selecting any option from the menu and then removing it.
You'll receive a notification for an "Internal Server Error," and the fallback block cannot be reset to an empty state.
```

### Logs

```bash
Oops! Something went wrong ... the server may had encountered an internal error. Please contact our support team if needed.
```

### PR DESCRIPTION
**Pull request by omarNaifer12**
The backend does not allow fallback_block to be null it only allows it to be a string.

Fixes #553 

# Type of change:

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] I have performed a self-review of my own code
- [x] New and existing unit tests pass locally with my changes

## Summary by CodeRabbit

- **Bug Fixes**
	- Refined the behavior of the settings input so that when no valid selection is made, it now returns an empty value for improved consistency in state management.

### CODE REVIEW

**Review by yassinedorbozgithub — APPROVED** [review]

**Review by MohamedAliBouhaouala — APPROVED** [review]

File: frontend/src/components/settings/SettingInput.tsx [hunk 1]
```diff
@@ -1,11 +1,12 @@
 /*
- * Copyright © 2024 Hexastack. All rights reserved.
+ * Copyright © 2025 Hexastack. All rights reserved.
  *
  * Licensed under the GNU Affero General Public License v3.0 (AGPLv3) with the following additional terms:
  * 1. The name "Hexabot" is a trademark of Hexastack. You may not use this name in derivative works without express written permission.
  * 2. All derivative works must include clear attribution to the original creator and software, Hexastack and Hexabot, in a prominent location (e.g., in the software's "About" section, documentation, and README file).
  */
 
+
```
Comment (yassinedorbozgithub) [inline frontend/src/components/settings/SettingInput.tsx:9]:
```suggestion
```

**Review by yassinedorbozgithub — CHANGES_REQUESTED** [review]

**Review by yassinedorbozgithub — APPROVED** [review]
