### PR TITLE
fix(frontend): enhance move blocks between categories logic

### LINKED ISSUE #1420: 🐛 [BUG] - enhance move transition animation logic
### Description

The idea is to enhance the transition logic.

### Reproduction steps

```bash
-
```

### Logs

```bash

```

### Browsers

_No response_

### OS

_No response_

### PR DESCRIPTION
**Pull request by yassinedorbozgithub**
# Motivation
The motivation of this PR is to enhance the move blocks logic.

Fixes #1420

# Type of change:
- [x] Bug fix (non-breaking change which fixes an issue)

## Summary by CodeRabbit

- New Features
  - Visual Editor adds URL-driven helpers to read/update editor state and remove block IDs.
  - Automatically selects a default category on first load.
  - Focus improvements: support focusing multiple blocks and retain smoother transitions from search/navigation.

- Refactor
  - Centralized category management via a dedicated category hook.
  - Moved URL and focus-related helpers into the shared editor context for consistent behavior across tabs, panels, create/move/delete flows.

### CODE REVIEW

File: frontend/src/components/visual-editor/v3/providers/VisualEditorProvider.tsx [hunk 1]
```diff
@@ -72,10 +74,32 @@ export const VisualEditorProvider: React.FC<VisualEditorContextProps> = ({
       }),
     });
   };
+  const getQuery = (key: string): string =>
+    typeof router.query[key] === "string" ? router.query[key] : "";
+  const updateVisualEditorURL = async (
+    category: string,
+    blockIds: string[] = [],
+  ) => {
+    const blockParam = blockIds.join ? `/${blockIds.join(",")}` : "";
```
Comment (marrouchi) [inline frontend/src/components/visual-editor/v3/providers/VisualEditorProvider.tsx]:
```suggestion
    const blockParam = Array.isArray(blockIds) && blockIds.length ? `/${blockIds.join(",")}` : "";
```
