### PR TITLE
fix(api): add Date support to flatten function

### LINKED ISSUE #1196: 🐛 [BUG] - Add Date support to flatten function
### Description

We can notice that the flatten function ignore Date (type object).
This behavior can cause issues.

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Logs

```bash

```

### Browsers

_No response_

### OS

_No response_

### PR DESCRIPTION
**Pull request by yassinedorbozgithub**
# Motivation
The main motivation of this PR are : 
- Add Date support to flatten function
- Add Unit test to cover the added logic

Fixes #1196 (HOTFIX)

# Type of change:
- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:
- [x] I have performed a self-review of my own code
- [x] I have added unit tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved handling of Date objects when flattening nested objects, ensuring Date values are preserved correctly in the flattened output.

* **Tests**
  * Added a test to verify that objects containing Date instances are flattened without altering the Date values.

### CODE REVIEW

File: api/src/utils/helpers/flatten.ts [hunk 1]
```diff
@@ -26,7 +26,12 @@ export const flatten = (
   for (const [key, value] of Object.entries(data)) {
     const path = prefix ? `${prefix}.${key}` : key;
 
-    if (typeof value === 'object' && value !== null && !Array.isArray(value)) {
+    if (
+      typeof value === 'object' &&
+      !(value instanceof Date) &&
+      value !== null &&
+      !Array.isArray(value)
```
Comment (marrouchi) [inline api/src/utils/helpers/flatten.ts]: Let's declare the function that does test on plain objects:
```ts
const isPlainObject = (val: unknown): val is Record<string, unknown> =>
  typeof val === 'object' &&
  val !== null &&
  !Array.isArray(val) &&            // not an Array
  Object.getPrototypeOf(val) === Object.prototype;  // direct Object.prototype
```

then you do :
```ts
if (isPlainObject(value)) {
      flatten(value, path, result);          // keep drilling
    } else {
      result[path] = value;                  // treat everything else as leaf
    }
```

**Review by medchedli — APPROVED** [review]
:+1:
