### PR TITLE
fix: logout

### LINKED ISSUE #594: When clicking on "Logout", sometimes the user doesn't get disconnected
Investigate the root cause of the issue (do not fix).

### PR DESCRIPTION
**Pull request by abdou6666**
# Motivation

This PR addresses the issue when users logs out, the dashboard displays for a second then page refreshes and logs out the user

Fixes #594

# Type of change:

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] I have performed a self-review of my own code

### CODE REVIEW

File: frontend/src/hooks/entities/auth-hooks.ts [hunk 1]
```diff
@@ -61,7 +62,10 @@ export const useLogout = (
 
       return await apiClient.logout();
     },
-    onSuccess: () => {},
+    onSuccess: async () => {
+      queryClient.removeQueries([CURRENT_USER_KEY]);
+      await logoutRedirection();
+    },
```
Comment (IkbelTalebHssan) [inline frontend/src/hooks/entities/auth-hooks.ts:68]: I have this minor suggestion 
```suggestion
onError: (error) => {
  toast.error(t("message.logout_failed"));
}
    },
```

**Review by marrouchi — APPROVED** [review]
👏

File: frontend/src/hooks/entities/auth-hooks.ts (hunk 1 above)
Comment (marrouchi) [reply frontend/src/hooks/entities/auth-hooks.ts:68]: +1

Comment (abdou6666) [reply frontend/src/hooks/entities/auth-hooks.ts:68]: @IkbelTalebHssan good idea i'll address it in different PR
