### PR TITLE
fix(frontend): disconnect from ws on logout [PART 1]

### LINKED ISSUE #612: Disconnect from WS on Logout
Investigate how to disconnect from chat widget WS and reload other opened tabs on logout.

## How to reproduce
1. Open the visual editor and Chat window
2. Duplicate the tab, and logout
3. Return to the first window, send messages to the chat.

### PR DESCRIPTION
**Pull request by yassinedorbozgithub**
# Motivation
The main motivation of this PR is to synchronize disconnection cross browser tabs 

- [x] Frontend disconnection via brodcastchannel
- [ ] API disconnection from the logout endpoint (disconnect all the pending web-socket connections)

Fixes #612

# Type of change:
- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:
- [x] I have performed a self-review of my own code
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by IkbelTalebHssan — APPROVED** [review]
Tested the way mentioned here https://github.com/Hexastack/Hexabot/issues/612 and the issue is resolved :heavy_check_mark:

**Review by abdou6666 — APPROVED** [review]

**Review by marrouchi — CHANGES_REQUESTED** [review]
Thanks @yassinedorbozgithub, 

More importantly, we need to disconnect the widget socket as well.

File: frontend/src/hooks/useBroadcastChannel.ts [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+  SECONDARY = "secondary",
+}
+
+export enum EBCEvent {
+  LOGOUT_END_SESSION = "logout-end-session",
+}
+
+export const useBroadcastChannel = ({
+  channelName,
+  initialValue,
```
Comment (marrouchi) [inline frontend/src/hooks/useBroadcastChannel.ts:22]: In which case do we provide initialValue?

File: frontend/src/hooks/useBroadcastChannel.ts [hunk 2]
```diff
@@ -0,0 +1,55 @@
...
+      if (mode === ETabMode.PRIMARY) {
+        setValue(event.data);
+        setMode(ETabMode.SECONDARY);
+      }
+    };
+
+    channel.postMessage(initialValue);
+
+    return () => {
+      channel.close();
```
Comment (marrouchi) [inline frontend/src/hooks/useBroadcastChannel.ts:45]:
```suggestion
      channel.onmessage = null; // Clean up the handler
      channel.close();
```

File: frontend/src/hooks/useBroadcastChannel.ts [hunk 3]
```diff
@@ -0,0 +1,55 @@
...
+  channelName,
+  initialValue,
+}: {
+  channelName: string;
+  initialValue?: EBCEvent;
+}) => {
+  const [value, setValue] = useState<EBCEvent | undefined>(initialValue);
+  const [mode, setMode] = useState<ETabMode>(ETabMode.PRIMARY);
+  const channel = useMemo(
+    () => new BroadcastChannel(channelName),
```
Comment (marrouchi) [inline frontend/src/hooks/useBroadcastChannel.ts:30]: We need to handle the edge case where browser doesn’t support BroadcastChannel.

**Review by marrouchi — CHANGES_REQUESTED** [review]
A couple of comments, have you tested when a tab becomes primary ?

File: frontend/src/hooks/useBroadcastChannel.ts [hunk 4]
```diff
@@ -0,0 +1,55 @@
...
+export const useBroadcastChannel = ({
+  channelName,
+  initialValue,
+}: {
+  channelName: string;
+  initialValue?: EBCEvent;
+}) => {
+  const [value, setValue] = useState<EBCEvent | undefined>(initialValue);
+  const [mode, setMode] = useState<ETabMode>(ETabMode.PRIMARY);
+  const channel = useMemo(
```
Comment (marrouchi) [inline frontend/src/hooks/useBroadcastChannel.ts:29]: Better to use ref here  :
  `const channelRef = useRef<BroadcastChannel | null>(null);`
and instanciate during useEffect()

File: frontend/src/hooks/useBroadcastChannel.ts [hunk 5]
```diff
@@ -0,0 +1,55 @@
...
+    () => new BroadcastChannel(channelName),
+    [channelName],
+  );
+
+  useEffect(() => {
+    channel.onmessage = (event) => {
```
Comment (marrouchi) [inline frontend/src/hooks/useBroadcastChannel.ts:35]: Is this possible ? `channel.addEventListener('message', handleMessage);`

**Review by marrouchi — CHANGES_REQUESTED** [review]

File: frontend/src/hooks/useBroadcastChannel.ts (hunk 1 above)
Comment (yassinedorbozgithub) [reply frontend/src/hooks/useBroadcastChannel.ts:22]: The motivation is that the logic can avoid extra rendering for example in the case of toggling dark/light themes (feature feature)

File: frontend/src/hooks/useBroadcastChannel.ts (hunk 3 above)
Comment (yassinedorbozgithub) [reply frontend/src/hooks/useBroadcastChannel.ts:30]: Yes it's working but we can investigating more about edge cases, compatibility it's very important. Tab focus it's a good idea as well

File: frontend/src/hooks/useBroadcastChannel.ts (hunk 5 above)
Comment (yassinedorbozgithub) [reply frontend/src/hooks/useBroadcastChannel.ts:35]: Yes for sure

**Comment by yassinedorbozgithub** [comment]
Hi @marrouchi, the feedback updates are applied :heavy_check_mark:

File: widget/src/hooks/useBroadcastChannel.ts [hunk 6]
```diff
@@ -0,0 +1,141 @@
...
+  handleMessage?: (event: MessageEvent) => void,
+  handleMessageError?: (event: MessageEvent) => void,
+): (data: T) => void {
+  const channelRef = React.useRef<BroadcastChannel | null>(null);
+
+  React.useEffect(() => {
+    if (typeof window !== "undefined" && "BroadcastChannel" in window) {
+      channelRef.current = new BroadcastChannel(channelName + "-channel");
+    }
+  }, [channelName]);
```
Comment (marrouchi) [inline widget/src/hooks/useBroadcastChannel.ts:50]:
```suggestion
  const channelRef = React.useRef<BroadcastChannel | null>(typeof window !== "undefined" && "BroadcastChannel" in window ? new BroadcastChannel(channelName + "-channel") : null);
```

File: widget/src/hooks/useBroadcastChannel.ts [hunk 7]
```diff
@@ -0,0 +1,141 @@
...
+  useChannelEventListener(channelRef.current, "message", handleMessage);
+  useChannelEventListener(
+    channelRef.current,
+    "messageerror",
+    handleMessageError,
+  );
+
+  return React.useCallback(
+    (data: T) => channelRef.current?.postMessage(data),
+    [channelRef.current],
```
Comment (marrouchi) [inline widget/src/hooks/useBroadcastChannel.ts:61]:
```suggestion
  return (data: T) => channelRef.current?.postMessage(data)
```

**Review by marrouchi — CHANGES_REQUESTED** [review]

File: widget/src/providers/ChatProvider.tsx [hunk 8]
```diff
@@ -453,6 +453,10 @@ const ChatProvider: React.FC<{
     handleSubscription,
   };
 
+  useBroadcastChannel("session", () => {
+    socketCtx.socket.disconnect();
+  });
```
Comment (marrouchi) [inline widget/src/providers/ChatProvider.tsx:458]: Shouldn't we check on the message "logout" ?

**Review by marrouchi — CHANGES_REQUESTED** [review]

File: widget/src/providers/ChatProvider.tsx (hunk 8 above)
Comment (yassinedorbozgithub) [reply widget/src/providers/ChatProvider.tsx]: Yes, the logic is updated to check the body of sent message
