### PR TITLE
Fix : Number settings gets saved as strings in MongoDB

### LINKED ISSUE #427: 🤔 [ISSUE] - Settings of type number get stored as string
### Description

Settings of type number get stored as strings. We may have the same issue for boolean.

### Reproduction steps

```bash
-
```

### Logs

_No response_

### Browsers

_No response_

### OS

_No response_

### PR DESCRIPTION
**Pull request by abdou6666**
# Motivation

This PR fixes the issue when updating a setting field that should be saved as Number and saved as String in MongoDB because mongoose middleware/hooks does not run by default on findOneAndUpdate

Fixes #427

# Type of change:

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

File: frontend/src/components/settings/index.tsx [hunk 1]
```diff
@@ -133,8 +133,14 @@ export const Settings = () => {
...
     const subscription = watch((values, { name }) => {
       const [group, label] = (name as string).split(".");
-
-      debouncedUpdate(group, label, values[group][label]);
+      const currentSettingValue = values[group][label] as any;
+      // if setting value is Number but typed string convert it to number
+      const settingValue =
+        typeof values[group][label] === "string" && isNaN(currentSettingValue)
+          ? values[group][label]
+          : Number(values[group][label]);
```
Comment (yassinedorbozgithub) [inline frontend/src/components/settings/index.tsx:141]:
```suggestion
       const setting = settings.find(
        (setting) => setting.group === group && setting.label === label,
      )?.value;
      // if setting value is Number but typed string convert it to number
      const settingValue =
        typeof setting === "number"
          ? Number(values[group][label])
          : values[group][label];
```
Hi @abdou6666, do you think maybe that we can do something like this to resolve the data save issue

File: frontend/src/components/settings/index.tsx [hunk 2]
```diff
@@ -133,8 +133,14 @@ export const Settings = () => {
   useEffect(() => {
     const subscription = watch((values, { name }) => {
       const [group, label] = (name as string).split(".");
-
-      debouncedUpdate(group, label, values[group][label]);
+      const currentSettingValue = values[group][label] as any;
```
Comment (marrouchi) [inline frontend/src/components/settings/index.tsx:136]: Let's rather use the rules in the "Controller" : 
```
rules={{ valueAsNumber: setting.type === 'number'}}
```

**Review by marrouchi — CHANGES_REQUESTED** [review]

File: api/src/setting/repositories/setting.repository.ts [hunk 3]
```diff
@@ -100,4 +99,62 @@ export class SettingRepository extends BaseRepository<Setting> {
...
+    } else if (type === SettingType.attachment) {
+      if (typeof value !== 'string' && typeof value !== null) {
+        throw new Error(
+          'Setting Model (attachement): Value must be a string or null !',
+        );
+      }
+    } else if (type === SettingType.secret && typeof value !== 'string') {
+      throw new Error('Setting Model (secret) : Value must be a string');
+    } else if (type === SettingType.select && typeof value !== 'string') {
+      throw new Error('Setting Model (select): Value must be a string array!');
```
Comment (yassinedorbozgithub) [inline api/src/setting/repositories/setting.repository.ts:153]:
```suggestion
      throw new Error('Setting Model (select): Value must be a string');
```

**Review by yassinedorbozgithub — CHANGES_REQUESTED** [review]
