### PR TITLE
fix(frontend): resolve overlay component bottom

### LINKED ISSUE #1366: 🐛 [BUG] - overlay component extra bottom css property
### Description

We can notice that the Overlay component has a bottom CSS property that can be removed.

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Logs

```bash

```

### Browsers

_No response_

### OS

_No response_

### PR DESCRIPTION
**Pull request by yassinedorbozgithub**
# Motivation
The main motivation of this PR is to resolve the overlay CSS bottom property bug.

Fixes #1366

# Type of change:
- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:
- [x] I have performed a self-review of my own code
- [x] New and existing unit tests pass locally with my changes

## Summary by CodeRabbit

* **Style**
  * Set a minimum height for the data grid to ensure a consistent layout across views.
  * Updated custom alert styling by removing the bottom offset, refining on-screen positioning.

### CODE REVIEW

File: frontend/src/layout/themes/theme.ts [hunk 1]
```diff
@@ -253,7 +253,6 @@ export const theme = createTheme({
             alignItems: "center",
             minHeight: "300px",
```
Comment (marrouchi) [inline frontend/src/layout/themes/theme.ts:254]: Do we still need this minHeight ?

**Review by marrouchi — CHANGES_REQUESTED** [review]

File: frontend/src/layout/themes/theme.ts (hunk 1 above)
Comment (yassinedorbozgithub) [reply frontend/src/layout/themes/theme.ts:254]: Yes, this is the output without the minHeight CSS property
image
