### PR TITLE
fix: display contentType text-area fields in list block

### LINKED ISSUE #452: 🤔 [ISSUE] - Carousel/List Block: The subtitle field does not show "textarea" content fields
### Description

When adding a Carousel/List Block, the "subtitle" field in the message form does not show "textarea" content fields.

### Reproduction steps

```bash
1. Go to 'Knownledge Base > Content Types' and add a content type with an extra "body" field of type "Textarea
2. Go to "Visual Editor" and add a carousel/list block
3. Edito and go to 'Message', select the content type and check the "Subtitle" field
```

### Logs

```bash

```

### Browsers

_No response_

### OS

_No response_

### PR DESCRIPTION
**Pull request by abdou6666**
# Motivation

This PR addresses the issue in List Block contentTypes of type text-area aren't displayed as an option 
Fixes #452

# Type of change:

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] I have performed a self-review of my own code

### CODE REVIEW

File: frontend/src/components/visual-editor/form/ListMessageForm.tsx [hunk 1]
```diff
@@ -186,7 +186,9 @@ const ListMessageForm = () => {
               return (
                 <AutoCompleteSelect<ContentField, "label", false>
                   options={(contentType?.fields || []).filter(
-                    ({ type }) => ContentFieldType.TEXT === type,
+                    ({ type }) =>
+                      ContentFieldType.TEXT === type ||
+                      ContentFieldType.TEXTAREA === type,
```
Comment (marrouchi) [inline frontend/src/components/visual-editor/form/ListMessageForm.tsx:191]: Textarea should be available only in subtitle
```suggestion
                    ({ type }) => ContentFieldType.TEXT === type,
```

**Review by marrouchi — CHANGES_REQUESTED** [review]
