### PR TITLE
fix(api): resolve predefined create hooks bug

### LINKED ISSUE #1132: 🤔 [ISSUE] - API : Make sure "hook:entity:pre/postCreate" is used across the board
### Description

In certain cases, we are not using hook:<entity>:pre/postCreate. This is because, the event wasn't properly implemented.

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Logs

```bash

```

### Browsers

_No response_

### OS

_No response_

### PR DESCRIPTION
**Pull request by yassinedorbozgithub**
# Motivation
The main motivation of this PR is to use base-repository predefined hooks.

Fixes #1132

# Type of change:
- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:
- [x] I have performed a self-review of my own code
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: api/src/chat/repositories/label.repository.ts [hunk 1]
```diff
@@ -31,31 +30,4 @@ export class LabelRepository extends BaseRepository<
...
-                ...(created.label_id || {}),
-                ...result,
-              },
-            },
-          },
-        );
-      },
-    );
-  }
 }
```
Comment (MohamedAliBouhaouala) [inline api/src/chat/repositories/label.repository.ts:33]: label postCreate is no longer needed?

Comment (yassinedorbozgithub) [reply api/src/chat/repositories/label.repository.ts:33]: Nice catch, this logic is moved to the [hexabot-channel-messenger](https://github.com/Hexastack/hexabot-channel-messenger/pull/21/files) extension
image

File: api/src/nlp/repositories/nlp-value.repository.spec.ts [hunk 2]
```diff
@@ -180,4 +191,63 @@ describe('NlpValueRepository', () => {
       expect(sampleEntities.length).toEqual(0);
     });
   });
+
+  describe('postCreate', () => {
+    it('should create and attached a foreign_id to the create nlp value', async () => {
```
Comment (MohamedAliBouhaouala) [inline api/src/nlp/repositories/nlp-value.repository.spec.ts]:
```ts
it('should create and attach a foreign_id to the newly created nlp value', async () =>
```

File: api/src/nlp/repositories/nlp-value.repository.spec.ts [hunk 3]
```diff
@@ -180,4 +191,63 @@ describe('NlpValueRepository', () => {
...
+      nlpValueRepository.eventEmitter.once(
+        'hook:nlpValue:postCreate',
+        async (...[created]) => {
+          const spy1 = jest.spyOn(llmNluHelper, 'addValue');
```
Comment (MohamedAliBouhaouala) [inline api/src/nlp/repositories/nlp-value.repository.spec.ts]:
```ts
const helperSpy
```

File: api/src/nlp/repositories/nlp-value.repository.spec.ts [hunk 4]
```diff
@@ -180,4 +191,63 @@ describe('NlpValueRepository', () => {
...
+          const spy2 = jest.spyOn(nlpValueService, 'updateOne');
```
Comment (MohamedAliBouhaouala) [inline api/src/nlp/repositories/nlp-value.repository.spec.ts]:
```ts
const nlpValueServiceSpy
```

File: api/src/nlp/repositories/nlp-value.repository.spec.ts [hunk 5]
```diff
@@ -180,4 +191,63 @@ describe('NlpValueRepository', () => {
...
+      const intentNlpEntity = await nlpValueRepository.findOne(result.id);
+
+      expect(intentNlpEntity?.foreign_id).toBeDefined();
+      expect(intentNlpEntity).toEqualPayload(result, [
+        ...IGNORED_TEST_FIELDS,
+        'foreign_id',
+      ]);
+    });
+
+    it('should create and attached a foreign_id to the create nlp value with builtin true', async () => {
```
Comment (MohamedAliBouhaouala) [inline api/src/nlp/repositories/nlp-value.repository.spec.ts]:
```ts
it('should not create and attach a foreign_id to the newly created nlp value with builtin set to true')
```

File: api/src/nlp/repositories/nlp-entity.repository.spec.ts [hunk 6]
```diff
@@ -173,4 +178,54 @@ describe('NlpEntityRepository', () => {
       ]);
     });
   });
+
+  describe('postCreate', () => {
+    it('should not create and attached a foreign_id to the create nlp entity', async () => {
```
Comment (MohamedAliBouhaouala) [inline api/src/nlp/repositories/nlp-entity.repository.spec.ts]:
```ts
it('should  create and attach a foreign_id to the newly created nlp entity')
```

File: api/src/nlp/repositories/nlp-entity.repository.spec.ts [hunk 7]
```diff
@@ -173,4 +178,54 @@ describe('NlpEntityRepository', () => {
...
+      const intentNlpEntity = await nlpEntityRepository.findOne(result.id);
+
+      expect(intentNlpEntity?.foreign_id).toBeDefined();
+      expect(intentNlpEntity).toEqualPayload(result, [
+        ...IGNORED_TEST_FIELDS,
+        'foreign_id',
+      ]);
+    });
+
+    it('should not create and attached a foreign_id to the create nlp entity with builtin true', async () => {
```
Comment (MohamedAliBouhaouala) [inline api/src/nlp/repositories/nlp-entity.repository.spec.ts]:
```ts
it('should not create and attach a foreign_id to the newly created nlp entity with builtin set to true', async () =>
```

File: api/src/nlp/repositories/nlp-entity.repository.spec.ts [hunk 8]
```diff
@@ -173,4 +178,54 @@ describe('NlpEntityRepository', () => {
       ]);
     });
   });
+
+  describe('postCreate', () => {
+    it('should not create and attached a foreign_id to the create nlp entity', async () => {
+      nlpEntityRepository.eventEmitter.once(
+        'hook:nlpEntity:postCreate',
+        async (...[created]) => {
+          const spy1 = jest.spyOn(llmNluHelper, 'addEntity');
```
Comment (MohamedAliBouhaouala) [inline api/src/nlp/repositories/nlp-entity.repository.spec.ts]:
```ts
const helperSpy
```

File: api/src/nlp/repositories/nlp-entity.repository.spec.ts [hunk 9]
```diff
@@ -173,4 +178,54 @@ describe('NlpEntityRepository', () => {
...
+          const spy2 = jest.spyOn(nlpEntityService, 'updateOne');
```
Comment (MohamedAliBouhaouala) [inline api/src/nlp/repositories/nlp-entity.repository.spec.ts]:
```ts
const nlpEntityServiceSpy
```

**Review by MohamedAliBouhaouala — APPROVED** [review]

**Review by marrouchi — APPROVED** [review]
