### PR TITLE
[ISSUE] #19 Fix urls (trailing or missing slashes)

### LINKED ISSUE #19: 🐛 [BUG] - Extra Slash in Export URL
### Description

image

### Reproduction steps

```bash
1. Login
2. Go to 'NLP' in the left sidebar
3. Click on 'Export' button
4. Notice the extra slash in the url: '//nlpsample/export'
```

### Logs

_No response_

### Browsers

_No response_

### OS

_No response_

### PR DESCRIPTION
**Pull request by kartik1112**
# Motivation

Fixes #19 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (Storybook)
- [ ] I have added unit tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by yassinedorbozgithub — APPROVED** [review]

File: frontend/src/components/nlp/components/NlpSample.tsx [hunk 1]
```diff
@@ -285,7 +285,7 @@ export default function NlpSample() {
             ) ? (
               <Button
                 variant="contained"
-                href={`${publicRuntimeConfig.apiUrl}/nlpsample/export${
+                href={`${publicRuntimeConfig.apiUrl}nlpsample/export${
```
Comment (marrouchi) [inline frontend/src/components/nlp/components/NlpSample.tsx:288]: Thank you @kartik1112 for adressing this 🙏 

publicRuntimeConfig.apiUrl is a config value that can be passed as a env var.

This config could be missing a trailing slash. This would lead to have a link like the following : http://localhost:4000nlpsample/export/....


I suggest we add a helper function in the utils/URL.ts file : 
```ts
/**
 * Joins a base URL and a relative path to form a complete URL.
 *
 * @param baseUrl - The base URL (must include the protocol, e.g., 'http://', 'https://').
 * @param relativePath - The relative URL path to be appended to the base URL.
 * @returns The full URL as a string.
 */
function buildUrl(baseUrl: string, relativePath: string): string {
    // Check if baseUrl is a valid URL
    try {
        new URL(baseUrl);
    } catch {
        throw new Error(`Invalid base URL: ${baseUrl}`);
    }

    // Create and return the full URL
    const url = new URL(relativePath, baseUrl);
    return url.toString();
}

// Example usage:
const domain = 'https://example.com/some/path/';
const path = '../another/path';

const fullUrl = buildUrl(domain, path);

console.log(fullUrl); // Outputs: 'https://example.com/another/path'
```

If you could please search for other usages of "publicRuntimeConfig.apiUrl" so that it becomes the standard way of building urls in a safe way.

**Review by marrouchi — CHANGES_REQUESTED** [review]

File: frontend/src/utils/URL.ts [hunk 2]
```diff
@@ -26,3 +26,14 @@ export const getFromQuery = ({
...
+
+export const buildURL = (baseUrl: string, relativePath: string): string => {
+  try {
+    new URL(baseUrl);
+  } catch {
+    throw new Error(`Invalid base URL: ${baseUrl}`);
+  }
+  const url = new URL(relativePath, baseUrl);
+
+  return url.toString();
```
Comment (marrouchi) [inline frontend/src/utils/URL.ts:38]:
```suggestion
  try {
 
    const url = new URL(relativePath, baseUrl);

    return url.toString();
  } catch {
    throw new Error(`Invalid base URL: ${baseUrl}`);
  }
```

**Review by marrouchi — CHANGES_REQUESTED** [review]

**Review by marrouchi — APPROVED** [review]

**Review by medtaher123 — APPROVED** [review]
