### PR TITLE
fix(api): update lastvisit and retainedfrom defaultvalues

### LINKED ISSUE #1171: 🤔 [ISSUE] - incorrect lastvisit and retainedFrom defaultvalues
### Description

We can notice that **lastvisit** and **retainedFrom** defaultValues are incorrect

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Logs

```bash

```

### Browsers

_No response_

### OS

_No response_

### PR DESCRIPTION
**Pull request by yassinedorbozgithub**
# Motivation
The main motivation of this PR is to update lastvisit and retainedfrom defaultvalues.

Fixes #1171

# Type of change:
- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:
- [x] I have performed a self-review of my own code
- [x] New and existing unit tests pass locally with my changes

## Summary by CodeRabbit

* **Refactor**
  * Updated default date values for subscriber visit and retention timestamps to reflect the current date and time. No changes to user-facing functionality.

### CODE REVIEW

**Review by medchedli — APPROVED** [review]

**Review by marrouchi — APPROVED** [review]

File: api/src/utils/test/fixtures/subscriber.ts [hunk 1]
```diff
@@ -23,8 +23,8 @@ export const subscriberDefaultValues: TSubscriberFixtures['defaultValues'] = {
   timezone: 0,
   assignedTo: null,
   assignedAt: null,
-  lastvisit: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
-  retainedFrom: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
+  lastvisit: new Date(),
+  retainedFrom: new Date(),
```
Comment (marrouchi) [inline api/src/utils/test/fixtures/subscriber.ts:27]:
```suggestion
  lastvisit: new Date(),
  retainedFrom: new Date(),
```

I think this needs to be retested. The default value could be fixed to when the API has been started, having an arrow function may fix it `() => new Date()`

Comment (yassinedorbozgithub) [reply api/src/utils/test/fixtures/subscriber.ts:27]: After double checking the **lastvisit**, **retainedFrom** fields will got a dynamic value reflecting the date of the run of the unit test, all the fixtures have static values of those fields.

Comment (marrouchi) [reply api/src/utils/test/fixtures/subscriber.ts:27]: Please perform a call with a setInterval() 

@medchedli can you test as well ?

Comment (yassinedorbozgithub) [reply api/src/utils/test/fixtures/subscriber.ts:27]: Hi @marrouchi, i have tested the output values the lastvisit, retainedFrom fields from the unit test to check if the it's static or not kindly find the screen recording bellow 
<video src="https://github.com/user-attachments/assets/e873e2a1-f739-4db2-8e4a-01054a2030e3"></video>

Comment (yassinedorbozgithub) [reply api/src/utils/test/fixtures/subscriber.ts:27]: Test with setInterval
<video src="https://github.com/user-attachments/assets/bba19fb5-150e-45b2-babf-560b8838639e"></video>

Comment (marrouchi) [reply api/src/utils/test/fixtures/subscriber.ts:27]: Sorry about the confusion

Comment (yassinedorbozgithub) [reply api/src/utils/test/fixtures/subscriber.ts:27]: No worries :pray: 
it was a good opportunity for me to share more details about the PR updates
