### PR TITLE
fix(frontend): resolve block list edit form bug

### LINKED ISSUE #575: 🐛 [BUG] - block list is not loading the full content
### Description

We can notice that we create a new block list, assign to it a content and selecting some Fields Map for example the title field. 
After refreshing the page and opening the edit model of this same block the data will not be loaded from the first try. 
 

### Reproduction steps

```bash
1. Go to Visual Editor
2. Create a new Block List
3. Edit this block 
4. Select a content 
5. Select a Fields Map field (title field for example)
6. Submit the update
7. Refresh the page and open this same block edit page to check the bug
```

### Logs

_No response_

### Browsers

Chrome

### OS

Linux

### PR DESCRIPTION
**Pull request by yassinedorbozgithub**
# Motivation
This PR main motivation is to resolve the missing default values for the list block edit modal.

Fixes #575

# Type of change:
- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:
- [x] I have performed a self-review of my own code
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by IkbelTalebHssan — APPROVED** [review]

File: frontend/src/components/visual-editor/form/ListMessageForm.tsx [hunk 1]
```diff
@@ -181,17 +181,19 @@ const ListMessageForm = () => {
             }}
             defaultValue={content?.fields?.title}
             render={({ field }) => {
-              const { onChange, ...rest } = field;
+              const { onChange, value, ...rest } = field;
+              const options = (contentType?.fields || []).filter(
```
Comment (MohamedAliBouhaouala) [inline frontend/src/components/visual-editor/form/ListMessageForm.tsx:185]: can't we put it in a seperate method to avoid code redundancy? getOptions(contentfieldtype) for example?

Comment (MohamedAliBouhaouala) [inline frontend/src/components/visual-editor/form/ListMessageForm.tsx:185]: can't we put it in a seperate method to avoid code redundancy? getOptions(contentfieldtype) for example?

Comment (yassinedorbozgithub) [reply frontend/src/components/visual-editor/form/ListMessageForm.tsx:185]: Yes, i think so it's a good idea

**Review by marrouchi — APPROVED** [review]
