### PR TITLE
Fixed carousel buttons not visible on dark image (black) and opening attachment from the inbox croping the image

### LINKED ISSUE #584: 🐛 [BUG] - Chat Widget Minor CSS issues
### Description

- carousel buttons do not display on dark image (black)
- opening attachment from the inbox crop the image

### PR DESCRIPTION
**Pull request by Rucha-Ambaliya**
# Motivation

Carousel Buttons: Improved visibility of carousel navigation buttons when displayed over dark or black images by adding a contrasting background and hover effect.
Inbox Attachments: Resolved image cropping issue when opening attachments from the inbox by adjusting the container styling and ensuring proper aspect ratio.

Fixes #584

# Type of change:

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by yassinedorbozgithub — CHANGES_REQUESTED** [review]
Hi @Rucha-Ambaliya, first of all thank you for your contribution :rocket: 
Can you explore the possibility to have responsive image base on the end user resolution using CSS properties ?
In general there is three cases to test to check if it's the expected behavior : 
- Test with an image having a 1:1 aspect (squared resolution)
- Test with an image having a 9:16 aspect (vertical resolution)
- Test with an image having a 16:9 aspect (horizontal resolution)

**Comment by Rucha-Ambaliya** [comment]
> Hi @Rucha-Ambaliya, first of all thank you for your contribution 🚀 Can you explore the possibility to have responsive image base on the end user resolution using CSS properties ? In general there is three cases to test to check if it's the expected behavior :
> 
> * Test with an image having a 1:1 aspect (squared resolution)
> * Test with an image having a 9:16 aspect (vertical resolution)
> * Test with an image having a 16:9 aspect (horizontal resolution)

No problem! I'll test it with different ratios and will share with you! Is it okay if I change height of modal as well, or should I keep it as it is? I think reducing it will be better since it will remove the need to scroll it and will be cleaner approach!

**Comment by yassinedorbozgithub** [comment]
> > Hi @Rucha-Ambaliya, first of all thank you for your contribution 🚀 Can you explore the possibility to have responsive image base on the end user resolution using CSS properties ? In general there is three cases to test to check if it's the expected behavior :
> > 
> > * Test with an image having a 1:1 aspect (squared resolution)
> > * Test with an image having a 9:16 aspect (vertical resolution)
> > * Test with an image having a 16:9 aspect (horizontal resolution)
> 
> No problem! I'll test it with different ratios and will share with you! Is it okay if I change height of modal as well, or should I keep it as it is? I think reducing it will be better since it will remove the need to scroll it and will be cleaner approach!

The mentioned aspects are to test the image viewer behavior, i believe that we don't expected to have a scroll in the viewer.
Thank you for you reactivity :raised_hands: 
Wish you a good luck :technologist:

**Comment by Rucha-Ambaliya** [comment]
[Video](https://drive.google.com/file/d/1ziPbWlWBqDC6krKL86S_ofLnesv8V_mv/view?usp=drive_link)

Let me know if any changes are needed! Also if you don't mind, may I know whom should I tag for issue assignment, PR review or anything else except the one who created the issue for earlier response?

**Comment by yassinedorbozgithub** [comment]
> Thank you!
> 
> [Video](https://drive.google.com/file/d/1ziPbWlWBqDC6krKL86S_ofLnesv8V_mv/view?usp=drive_link)
> 
> Let me know if any changes are needed! Also if you don't mind, may I know whom should I tag for issue assignment, PR review or anything else except the one who created the issue for earlier response?

Well done @Rucha-Ambaliya, 
This is update is perfect :rocket:

**Comment by Rucha-Ambaliya** [comment]
Thank you so much😊

Let me push my commit then!

**Review by yassinedorbozgithub — APPROVED** [review]

**Comment by Rucha-Ambaliya** [comment]
@yassinedorbozgithub Any update?

**Comment by yassinedorbozgithub** [comment]
Hi @Rucha-Ambaliya, thank you for being active in Hexabot project. 
To maintain high code quality and confirm the changes work as expected, each pull request must receive at least two approvals before being merged.

**Comment by yassinedorbozgithub** [comment]
Hi @Rucha-Ambaliya, be sure we will be tagged as the review process progresses :white_check_mark: 
it depends on the team's workload but usually it doesn't take long :rocket:

File: frontend/src/components/inbox/components/AttachmentViewerForm.tsx [hunk 1]
```diff
@@ -23,8 +23,8 @@ export const AttachmentViewerForm: FC<
     <Wrapper {...WrapperProps}>
       {/* eslint-disable-next-line @next/next/no-img-element */}
       <img
-        width="auto"
-        height={800}
+        width="100%"
+        height={400}
         style={{
           cursor: "pointer",
           objectFit: "contain",
```
Comment (medchedli) [inline frontend/src/components/inbox/components/AttachmentViewerForm.tsx:30]: This way, the image will scale according to its natural dimensions while respecting the container width and staying within a reasonable maximum height.

```suggestion
        style={{
          cursor: "pointer",
          objectFit: "contain",
          maxHeight: "80vh", // Use viewport-relative unit instead of fixed height
```

**Comment by Rucha-Ambaliya** [comment]
I’ve made the necessary changes. Is everything okay now?



https://github.com/user-attachments/assets/1f59dde3-110f-4bd1-8fde-0c9f1b9b3d5d


Note: Setting it to 80vh caused an overflow, so I reduced it!

**Comment by medchedli** [comment]
> Note: Setting it to 80vh caused an overflow, so I reduced it!

I'm not seeing the overflow you mentioned with `maxHeight `value. However, I do agree that the `AttachmentViewerForm `is growing too tall.

**Comment by Rucha-Ambaliya** [comment]
> > Note: Setting it to 80vh caused an overflow, so I reduced it!
> 
> I'm not seeing the overflow you mentioned with `maxHeight `value. However, I do agree that the `AttachmentViewerForm `is growing too tall, and it's maybe better to set it to `70vh`

It might have happened because of the height of my laptop's screen. Thanks for your review!

By the way, when can I expect this PR to be merged?"
