### PR TITLE
fix(api): block prototype pollution in search filter, sort, and update paths

### LINKED ISSUE #1919: TypeORM search filter pipe : potential prototype-polluting function
packages/api/src/utils/pipes/typeorm-search-filter.pipe.ts:
```ts
      cursor = cursor[segment] as Record<string, unknown>;
    }

    cursor[segments[segments.length - 1]] = value;
```

To fix the prototype pollution risk in assignNestedWhereValue, we must block unsafe key names from being set as object properties. Specifically, we should prevent assigning to property names "__proto__", "constructor", and "prototype" at any nesting level. The best place to do this is in the loop where segment is assigned as a property, and likewise when the last path segment is used for the final assignment. Add a guard to skip (or throw) if any segment equals one of these forbidden names. This ensures that even if path is attacker-controlled, these dangerous property names cannot be assigned deeply into the object, protecting against prototype pollution. All changes should be confined to the assignNestedWhereValue method in packages/api/src/utils/pipes/typeorm-search-filter.pipe.ts.

### PR DESCRIPTION
**Pull request by anis-marrouchi**
## Summary

- Centralizes forbidden-segment detection (`__proto__`, `constructor`, `prototype`) in a shared `hasForbiddenSegment()` helper
- Guards `parseSort()` — rejects sort fields containing forbidden segments
- Guards `assignNestedWhereValue()` — skips where-clause assignments with forbidden paths
- Guards `mergeWhereObjects()` — ignores forbidden keys during object merge
- Guards `updateOne()` in `BaseOrmRepository` — skips flattened update paths with forbidden segments

## Addressing maintainer feedback

Per @marrouchi's [comment on PR #1931](https://github.com/Hexastack/Hexabot/pull/1931):
1. ✅ Applied `FORBIDDEN_KEYS` check in `parseSort` method
2. ✅ Scanned all other pipes — only `typeorm-search-filter.pipe.ts` and `base-orm.repository.ts` needed guarding (other pipes like `populate`, `uuid`, `zod`, `io-message` don't process untrusted nested property paths)
3. ✅ Centralized the check in `packages/api/src/utils/helpers/safe-property-path.ts`

## Files changed

| File | Change |
|------|--------|
| `packages/api/src/utils/helpers/safe-property-path.ts` | New centralized helper |
| `packages/api/src/utils/helpers/safe-property-path.spec.ts` | 11 parameterized tests |
| `packages/api/src/utils/pipes/typeorm-search-filter.pipe.ts` | Guards in `parseSort`, `assignNestedWhereValue`, `mergeWhereObjects` |
| `packages/api/src/utils/pipes/typeorm-search-filter.pipe.spec.ts` | 6 prototype pollution prevention tests |
| `packages/api/src/utils/generics/base-orm.repository.ts` | Guard in `updateOne` flattened path |

## Test plan

- [x] `hasForbiddenSegment` detects `__proto__`, `constructor`, `prototype` as single segments and in dotted paths
- [x] `hasForbiddenSegment` allows safe paths like `constructorName`, `user.email`
- [x] Sort with `__proto__.polluted asc` falls back to default sort
- [x] Where clause with forbidden field is silently ignored
- [x] Global `Object.prototype` remains unpolluted after all attack vectors
- [x] All existing tests continue to pass
- [x] Lint + typecheck clean

Closes #1919

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved security: blocks unsafe property paths to prevent prototype-pollution via updates, sorting, and nested filtering; unsafe sort/where fields are ignored and nested writes aborted.

* **Tests**
  * Added tests validating prototype-pollution prevention across sorting, nested where construction, and update operations.

### CODE REVIEW

**Comment by anis-marrouchi** [comment]
Hey @marrouchi 👋 — this PR addresses your feedback from #1931:

1. **`FORBIDDEN_KEYS` in `parseSort`** — done ✅
2. **Scanned other pipes** — only `typeorm-search-filter.pipe.ts` and `base-orm.repository.ts` needed guarding (other pipes don't process untrusted nested property paths) ✅
3. **Centralized the check** — `hasForbiddenSegment()` in `safe-property-path.ts`, uses `lodash/toPath` to catch both dot and bracket notation (`a[__proto__].b`) ✅

CodeRabbit flagged two nitpicks about adding bracket-notation test cases — happy to add those if the overall approach looks right to you.

**Before we invest more time:** could you do a quick directional review? Specifically:
- Is the scope correct (search filter pipe + base-orm `updateOne`), or should we cover additional surfaces?
- Is the silent-skip behavior acceptable (forbidden paths are ignored rather than throwing)?
- Any preferences on where the helper should live?

Want to make sure we're aligned before polishing. Thanks! 🙏

File: packages/api/src/utils/generics/base-orm.repository.ts [hunk 1]
```diff
@@ -330,7 +331,9 @@ export abstract class BaseOrmRepository<
         ) as Record<string, unknown>;
         const target = entity as Record<string, unknown>;
         for (const [path, value] of Object.entries(flattenedUpdates)) {
-          set(target, path, value);
+          if (!hasForbiddenSegment(path)) {
+            set(target, path, value);
+          }
```
Comment (marrouchi) [inline packages/api/src/utils/generics/base-orm.repository.ts]: Thanks @anis-marrouchi 

Let's undo this change plz 🙏

**Review by marrouchi — CHANGES_REQUESTED** [review]

File: packages/api/src/utils/generics/base-orm.repository.ts (hunk 1 above)
Comment (anis-marrouchi) [reply packages/api/src/utils/generics/base-orm.repository.ts]: Done — reverted in 6033cb7. The `base-orm.repository.ts` change is removed, keeping the fix scoped to the search filter pipe only.

**My reasoning for why this makes sense:** `updateOne` receives data that has already passed through NestJS validation pipes and DTOs — it's trusted internal data by that point. Sanitization belongs at the input boundary (the pipes), not deep in the repository layer. Guarding there also risks silent data loss if a legitimate flattened field path were ever to match.

**A broader ask:** I'm an AI coding agent contributing to Hexabot, and I want to respect the project's conventions and architectural boundaries. Are there any unwritten rules or patterns I should be aware of? For example:
- Which layers should handle input sanitization vs. trust validated data?
- Any files/modules that are considered stable and shouldn't be touched without discussion?
- Preferred patterns for security hardening (throw vs. silent skip, centralized vs. inline)?

This would help me make better-scoped contributions going forward. Thanks! 🙏

Comment (marrouchi) [reply packages/api/src/utils/generics/base-orm.repository.ts]: Your reasoning was partly right, cause this should not only cover updateOne(), it affects also the create() and other DB write operations as well. 

I suggest you open a new issue and address this issue in a holistic fashion.
