### PR TITLE
fix(frontend): align BlockFormProvider method prop and the useForm typing

### LINKED ISSUE #903: 🐛 [BUG] - BlockForm useForm typing
### Description

We can notice that for `BlockForm` components, the typing of the `useForm` hook is not aligned with the typing of `UseFormReturn`.

### PR DESCRIPTION
**Pull request by yassinedorbozgithub**
# Motivation
The main motivation is to align the typing of the BlockFormProvider method prop with the useForm hook typing.

Fixes #903

# Type of change:
- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:
- [x] I have performed a self-review of my own code

## Summary by CodeRabbit

- **Chores**
  - Updated legal information to align with the current year.
  
- **Refactor**
  - Streamlined internal definitions to enhance clarity and maintainability.

These behind-the-scenes improvements ensure a cleaner, more up-to-date foundation for future enhancements while maintaining stable functionality for end-users.

### CODE REVIEW

File: frontend/src/components/visual-editor/form/BlockFormProvider.tsx [hunk 1]
```diff
@@ -23,7 +23,7 @@ function BlockFormProvider({
   methods,
   block,
 }: {
-  methods: UseFormReturn<IBlockAttributes, any, undefined>;
+  methods: UseFormReturn<IBlockAttributes>;
```
Comment (abdou6666) [inline frontend/src/components/visual-editor/form/BlockFormProvider.tsx:26]: I've noticed that the useBlock hook doesn't handle the case where it's used outside of its provider. Since useContext(BlockContext) can return undefined in that scenario, I think the hook should explicitly check for this and throw an exception to avoid unexpected behavior. What do you think?

```
// current implementation 
export const useBlock = () => useContext(BlockContext);
```
```
// improved implementation 
export const useBlock = () => {
 const context = useContext(BlockContext);
 if(!context){
  throw new Error('useBlock must be used inside BlockContext.Provider');
 }
 return context;
}
```

**Review by abdou6666 — CHANGES_REQUESTED** [review]

**Comment by abdou6666** [comment]
image

File: frontend/src/components/visual-editor/form/BlockFormProvider.tsx (hunk 1 above)
Comment (yassinedorbozgithub) [reply frontend/src/components/visual-editor/form/BlockFormProvider.tsx:26]: Hi @abdou6666, a dedicated [issue](https://github.com/Hexastack/Hexabot/issues/911) is created for the mentioned update

**Review by abdou6666 — APPROVED** [review]

**Review by MohamedAliBouhaouala — APPROVED** [review]
