### PR TITLE
fix: restrict paste content to have text format+don't lose old text

### LINKED ISSUE #242: 🐛 [BUG] - widget pasting text replace the old text content
### Description
We can notice that when we past a text content in the widget text field the old text content is replaced

### Issue Demonstration
<video src="https://github.com/user-attachments/assets/3368d095-35f2-47f0-be68-22282692b5c3" />

### Reproduction steps

```bash
1. Go to Visual Editor
2. Copy a text
3. Paste the text in the widget
4. Paste other text
5. Notice the paste issue
```

### Logs

_No response_

### Browsers

_No response_

### OS

_No response_

### PR DESCRIPTION
**Pull request by yassinedorbozgithub**
# Motivation
The main motivation of this update is to fix the issue happening the text field of the widget
More details are attached to the issue related to this PR.

Fixes #242

# Fix demonstration 
<video src="https://github.com/user-attachments/assets/67664797-43e5-4fb1-881b-8d65fd83fbba" />

# Type of change:
- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:
- [x] I have performed a self-review of my own code
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by marrouchi — APPROVED** [review]

**Review by IkbelTalebHssan — APPROVED** [review]

File: widget/src/components/UserInput.tsx [hunk 1]
```diff
@@ -6,25 +6,25 @@
...
+import EmojiButton from "./buttons/EmojiButton";
+import FileButton from "./buttons/FileButton";
+import LocationButton from "./buttons/LocationButton";
+import MenuButton from "./buttons/MenuButton";
+import SendButton from "./buttons/SendButton";
+import CloseIcon from "./icons/CloseIcon";
+import FileInputIcon from "./icons/FileInputIcon";
+import Suggestions from "./Suggestions";
+
+import "./UserInput.scss";
```
Comment (marrouchi) [inline widget/src/components/UserInput.tsx:27]: @yassinedorbozgithub Can we fix the linter to be consistent with frontend ? Maybe a seperate PR to lint:fix everything ?

**Review by marrouchi — CHANGES_REQUESTED** [review]

File: widget/src/components/UserInput.tsx (hunk 1 above)
Comment (yassinedorbozgithub) [reply widget/src/components/UserInput.tsx:27]: Sure, happy to do that like mentioned in a separate PR
