### PR TITLE
fix(frontend): add avatar handler icon

### LINKED ISSUE #1378: 💡 [REQUEST] - indicate whether the conversation handler bot/human
Add a visual marker (e.g., an icon or label) to show whether a conversation is currently managed by the bot or has been taken over by a human.
This allows users to quickly identify conversations that may need human intervention.

For conversations taken over by a human, display the name of the person who took over the conversation directly in the side list for better visibility.

### PR DESCRIPTION
**Pull request by yassinedorbozgithub**
# Motivation
The main motivation of this PR is to add an avatar indicator (subscriber or bot)

Fixes #1378

<video src="https://github.com/user-attachments/assets/d942d2af-4a5d-4679-9538-fe2b75257d12"></video>

image

## Summary by CodeRabbit

* **New Features**
  * Conversation list avatars now show the subscriber plus assigned teammate side-by-side with refined sizing and hover interaction for clearer context.
* **Refactor**
  * Avatar rendering centralized into a reusable Avatars component and adopted by the inbox conversation list for consistency and easier maintenance.

### CODE REVIEW

File: frontend/src/components/inbox/components/Avatars.tsx [hunk 1]
```diff
@@ -0,0 +1,37 @@
...
+        src={getAvatarSrc(apiUrl, EntityType.SUBSCRIBER, subscriber.id)}
+        title={`${subscriber.first_name} ${subscriber.last_name}`}
+      />
+      <Avatar
+        src={`${getAvatarSrc(
+          apiUrl,
+          EntityType.USER,
+          subscriber.assignedTo || "",
+        )}?color=${color}`}
+      />
```
Comment (medchedli) [inline frontend/src/components/inbox/components/Avatars.tsx]:
```suggestion
      <Avatar
        title={subscriber.assignedTo ? "Assigned Human Agent" : "Bot"}
        src={`${getAvatarSrc(
          apiUrl,
          EntityType.USER,
          subscriber.assignedTo || "",
        )}?color=${color}`}
      />
```

**Review by marrouchi — APPROVED** [review]
